name: CI/CD
on:
  push:
    branches: [ "main" ]
jobs:
  backend-lint:
    runs-on: macos-latest
    name: backend-lint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - run: |
          go get ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ./.
          args: --issues-exit-code=0
          skip-cache: true
          skip-pkg-cache: true
          skip-build-cache: true

  backend-build:
    runs-on: macos-latest
    needs:
      - backend-lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - run: go mod download
      - name: Build
        run: GOOS=linux go build ./cmd/microservice
      - name: Test
        run: go test -v ./...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: false

  deploy:
    runs-on: ubuntu-latest
    needs:
      - backend-build
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          # change cd to your destination
          script: |
            cd /var/www/kjushka/microservice
            git pull origin main
            git status
            docker-compose down -v 
            docker-compose up --build -d